services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api/todo-api:/app
    ports:
      - "3000:3000"
    networks:
      - app-network

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front/todo-front:/app
    ports:
      - "4000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
